# Created with https://github.com/dart-lang/mono_repo
language: dart

jobs:
  include:
    - stage: analyzer_and_format
      script: ./tool/travis.sh dartfmt dartanalyzer
      env: PKG="packages/web_socket_io"
      dart: dev
    - stage: test_vm
      script: ./tool/travis.sh test_vm
      env: PKG="packages/web_socket_io"
      dart: dev
    - stage: analyzer_and_format
      script: ./tool/travis.sh dartfmt dartanalyzer
      env: PKG="packages/web_socket"
      dart: dev
    - stage: test_vm
      script: ./tool/travis.sh test_vm
      env: PKG="packages/web_socket"
      dart: dev

stages:
  - analyzer_and_format
  - test_vm

# Only building master means that we don't run two builds for each pull request.
branches:
  only: [master]

cache:
  directories:
    - $HOME/.pub-cache