name: tekartik_web_socket
description: Web socket core
version: 0.3.0
publish_to: none
#homepage: https://www.example.com
#author: alex <email@example.com>

environment:
  sdk: ^3.5.0

dependencies:
  http: any
  tekartik_common_utils:
    git:
      url: https://github.com/tekartik/common_utils.dart
      ref: dart3a
    version: '>=0.9.3+2'
  web_socket_channel: '>=2.4.0'
  stream_channel: '>=2.1.0-0'

dev_dependencies:
  test: '>=1.0.0'
  dev_build: any
  process_run:
