name: tekartik_web_socket_support
description: Web socket support project
version: 0.0.1
publish_to: none
# homepage: https://www.example.com
#

environment:
  sdk: '>=2.12.0 <3.0.0'

#dependencies:
#  path: ^1.6.0

dev_dependencies:
  dev_test:
  test: ^1.6.0
  tekartik_common_utils:
    git:
      url: https://github.com/tekartik/common_utils.dart
      ref: dart2_3
  process_run:
  path: