name: tekartik_web_socket_support
description: Web socket support project
version: 0.0.1
publish_to: none
# homepage: https://www.example.com
#

environment:
  sdk: ^3.6.0

#dependencies:
#  path: ^1.6.0

dev_dependencies:
  dev_build: ">=1.1.0+2"
  test: ">=1.24.0"
  tekartik_common_utils:
    git:
      url: https://github.com/tekartik/common_utils.dart
      ref: dart3a
  process_run: ">=1.2.1+1"
  path: ">=1.9.0"
resolution: workspace
