name: tekartik_web_socket_test
description: Platform test
version: 0.3.0
publish_to: none
#homepage: https://www.example.com
#author: alex <email@example.com>

environment:
  sdk: ^3.7.0

dependencies:
  tekartik_web_socket:
    git:
      url: https://github.com/tekartik/web_socket.dart
      path: web_socket
      ref: dart3a
    version: '>=0.2.2'
  process_run: ">=1.2.1+1"
  test: ">=1.24.0"

dev_dependencies:
  dev_build: ">=1.1.2"
  collection: ">=1.18.0"

resolution: workspace
