name: tekartik_web_socket_test
description: Platform test
version: 0.0.1
#homepage: https://www.example.com
#author: alex <email@example.com>

environment:
  sdk: '>=2.0.0-dev.54 <2.0.0'

dependencies:
  tekartik_common_utils:
    git: git://github.com/tekartik/common_utils.dart
  tekartik_web_socket:
    git:
      url: git://github.com/tekartik/web_socket.dart
      path: web_socket

dev_dependencies:
  test: ">=0.12.37"
  dev_test: any

dependency_overrides:
  tekartik_web_socket:
    path: ../web_socket