name: tekartik_web_socket_test
description: Platform test
version: 0.3.0
publish_to: none
#homepage: https://www.example.com
#author: alex <email@example.com>

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  tekartik_web_socket:
    git:
      url: git://github.com/tekartik/web_socket.dart
      path: web_socket
      ref: null_safety
    version: '>=0.2.2'
  process_run:

dev_dependencies:
  test: ">=1.2.0"
  dev_test: any
  collection: '>=1.14.10'

dependency_overrides:
  tekartik_web_socket:
    path: ../web_socket